Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

choco install googlechrome -y
choco install firefox -y
choco install brave -y
choco install bitwarden -y
choco install 7zip.install -y
choco install telegram.install -y
choco install powertoys -y
choco install rufus -y
choco install obs-studio -y
choco install vlc -y
choco install teamviewer -y
choco install protonvpn -y
choco install everything -y
choco install etcher -y
choco install typora -y
choco install fscapture -y
choco install windirstat -y
choco install discord.install -y
choco install win32diskimager.install -y
choco install adobereader -y
choco install burp-suite-free-edition -y
choco install curl -y
choco install winmerge -y
choco install git.install -y
choco install nmap -y
choco install nodejs.install -y
choco install postman -y
choco install github-desktop -y
choco install procexp -y
choco install procmon -y
choco install notepadplusplus.install -y
choco install putty.install -y
choco install winscp.install -y
choco install sublimetext4 -y
choco install docker-desktop -y
choco install ilspy -y
choco install dnspy -y
choco install intellijidea-community -y
choco install origin -y
choco install ubisoft-connect -y
choco install epicgameslauncher -y
choco install steam-client -y
choco install spotify -y
