#Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

choco install ccleaner -y
choco install chocolatey -y
choco install curl -y
choco install dotPeek -y
choco install driverbooster -y
choco install git.install -y
choco install javadecompiler-gui -y
choco install microsoft-teams -y
choco install nmap -y
choco install nodejs.install -y
choco install Opera -y
choco install postman -y
choco install procexp -y
choco install procmon -y
choco install rufus -y
choco install servicebusexplorer -y
choco install sublimetext3 -y
choco install googlechrome -y
choco install firefox -y
choco install vlc -y
choco install notepadplusplus.install -y
choco install putty.install -y
choco install 7zip -y
choco install teamviewer -y
choco install sql-server-management-studio -y
choco install winscp.install -y
choco install dotnetcore-sdk -y
choco install vscode -y
choco install spotify -y
choco install everything -y
choco install telegram.install -y
choco install docker-desktop -y
choco install ilspy -y
choco install anydesk -y
choco install etcher -y
choco install burp-suite-free-edition -y
choco install microsoft-windows-terminal -y
choco install jetbrainstoolbox -y
choco install typora -y
choco install sublimemerge -y
choco install fscapture -y
choco install dnspy -y
