Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

choco install curl -y
choco install git.install -y
choco install nmap -y
choco install nodejs.install -y
choco install postman -y
choco install github-desktop -y
choco install procexp -y
choco install procmon -y
choco install visualstudio2019community -y
choco install rufus -y
choco install googlechrome -y
choco install bitwarden -y
choco install firefox -y
choco install vlc -y
choco install notepadplusplus.install -y
choco install putty.install -y
choco install 7zip.install -y
choco install teamviewer -y
choco install winscp.install -y
choco install protonvpn -y
choco install dotnetcore-sdk -y
choco install vscode.install -y
choco install spotify -y
choco install everything -y
choco install telegram.install -y
choco install docker-desktop -y
choco install ilspy -y
choco install etcher -y
choco install burp-suite-free-edition -y
choco install microsoft-windows-terminal -y
choco install typora -y
choco install fscapture -y
choco install dnspy -y
choco install intellijidea-community -y
choco install windirstat -y
choco install win32diskimager.install -y
choco install discord.install -y
